# Generated by Django 4.2.16 on 2024-11-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_api', '0005_alter_todo_description_alter_todo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
