# Generated by Django 4.2.16 on 2024-11-28 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_api', '0006_todo_slug_alter_todo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='slug',
        ),
    ]
