databases:
  - name: dpg-ct41hk52ng1s73a1if60-a  # This should be the unique identifier for your Render database
    plan: free
    databaseName: todos_q5w5  # The database name used for your app
    user: todos_q5w5_user     # The database username used for your app

services:
  - type: web
    plan: free
    name: test-api
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn django_lms.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dpg-ct41hk52ng1s73a1if60-a  # Database identifier (make sure this is the correct value)
          property: connectionString      # This will automatically pick up the connection string for you
      - key: SECRET_KEY                 # You might want to name it more clearly, such as SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
