databases:
  - name: dpg-ct41hk52ng1s73a1if60-a
    plan: free
    databaseName: todos_q5w5
    user: todos_q5w5_user

services:
  - type: web
    plan: free
    name: test-api
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn django_lms.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: todos_q5w5
          property: connectionString
      - key: Aks748z3Z8YsFyi2uOv2fxuXUeUZMKMn
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4